### ISSUE TITLE
get_metadata(ribo) should return metadata of the ribo object 

### ISSUE THREAD

**Issue by hakanozadam** [ribosomeprofiling/riboR_alpha#1]
When no experiment name is given:

`get_metadata(ribo_object)`

returns 
"Error in name %in% exp.list : argument "name" is missing, with no default".

It should return the metadata of the root ribo file if no experiment is given.

**Comment by hakanozadam** [comment]
When I tried it with the sample.ribo (inside test/sample/data)
I didn't see the metadata of the sample ribo file. It only displayed the standard attributes.
I was expecting to see :

aligner: bowtie2
deduplicated: true
mapq_threshold: 3

Are we going to the metadata attribute of the sample.ribo and displaying them?
I think the answer is no. I think it is because we are returning only the attributes without metadata

Lines 96-09 in info_functions.R
`  if (is.null(name)) {
    attributes <- get_attributes(ribo.object)
    return(data.table(attribute = names(attributes), value = attributes))`

**Comment by hakanozadam** [comment]
Let's use [yaml](https://github.com/viking/r-yaml) package for this.

Something like
`parsed_metadata  <- yaml.load(  ribo_metadata_attiribute )`
will return what we need for this.

**Comment by mjgeng** [comment]
I did make changes to the get_metadata function. If present, any of the fields in the metadata attributes are read in and added into a small data.table of the other root file attributes. This arrangement allows for easier printing.

**Comment by mjgeng** [comment]
For the time being, the get_metadata() function just returns a raw list of all of the attributes, including the metadata. I will look into printing a neater format, perhaps by collapsing the list.

**Comment by hakanozadam** [comment]
Works and prints great!
