### ISSUE TITLE
data.table needs to be loaded for riboR package

### ISSUE THREAD

**Issue by hakanozadam** [ribosomeprofiling/riboR_alpha#10]
After a fresh installation of the package I tried

`library("ribor")`
`green <- ribo("green.ribo")`
`green`
**Error in as.data.table(experiment.info) :** 
  **could not find function "as.data.table"**

Loading *data.table* package manually solved the problem.

I think we need to import data.table package when ribor is loaded.

**Comment by mjgeng** [comment]
Yes. I forgot to put @importFrom on the print method.
