### ISSUE TITLE
get_region_counts Default value for Region variable

### ISSUE THREAD

**Issue by cancenik** [ribosomeprofiling/riboR_alpha#13]
We should have the default value for the region parameter to be everything.

**Comment by mjgeng** [comment]
This was added in the most recent push. If there are any issues, please let me know!

**Comment by hakanozadam** [comment]
Yes, it is returning all regions when regions parameter is left unspecified.
Let's add a test case for this. More explicitly, we call **get_region_counts** without regions and make sure that all regions are returned.
