### ISSUE TITLE
Working R versions

### ISSUE THREAD

**Issue by hakanozadam** [ribosomeprofiling/riboR_alpha#14]
Based on our recent trials, it turns out this package need R 3.6 (or later).

Can we enforce this in the installation?

Also, we have to state this very clearly in the documentation.

**Comment by mjgeng** [comment]
Yes! It's very simple. I just have to update the DESCRIPTION file. I began developing the package with R 3.4.0, and I never changed the dependency. In fact, the bioconductor testing package will actually require R(>=3.6.0).

**Comment by mjgeng** [comment]
I made changes to the DESCRIPTION file in the most recent push. ribor is now dependent on version 3.6.0 or later of R. If the problem is still apparent on versions before 3.6.0, then please let me know.
