### ISSUE TITLE
Error in `*tmp*`[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by ijhoskins** [ribosomeprofiling/riboR_alpha#16]
Tried to import a ribofile and ran into an index error.

```
ingolia_ribo<- ribor::ribo("/Users/ianhoskins/UT_grad/Cenik_lab/ribo_testing/CBS.ribofile3")
Error in `*tmp*`[[i]] : subscript out of bounds
```

Here's a test ribofile. I had to add the txt extension so I could upload to GitHub.
[CBS.ribofile3.txt](https://github.com/ribosomeprofiling/riboR_alpha/files/3341090/CBS.ribofile3.txt)

**Comment by mjgeng** [comment]
The issue is resolved on the current build.

**Comment by ijhoskins** [comment]
Good work @mjgeng ! Lemme know if I can help test any further.
