### ISSUE TITLE
get_coverage not working

### ISSUE THREAD

**Issue by hakanozadam** [ribosomeprofiling/riboR_alpha#19]
cov <- get_coverage(name = "MYC-206",
+                     range.lower = 28,
+                     range.upper = 32,
+                     length = TRUE,
+                     alias = TRUE,
+                     tidy = TRUE,
+                     experiments = has.coverage)
Error in initialize_coverage(ribo.object, alias, range.lower, range.upper,  : 
  argument "ribo.object" is missing, with no default

**Comment by mjgeng** [comment]
I believe that you need to set the ribo.object alongside all of the parameters unless it was accidentally removed in the copy and paste from RStudio.

**Comment by hakanozadam** [comment]
Sorry, you are right. I forgot the ribo object....
