### ISSUE TITLE
plot_metagene() x-axis ticks

### ISSUE THREAD

**Issue by hakanozadam** [ribosomeprofiling/riboR_alpha#5]
plot_metagene function has ticks every 25 nucleotides.

We can place the ticks every 10 nucleotides by default. 
Maybe user can set the tick interval?

**Comment by hakanozadam** [comment]
We need to revisit this because I see the same behavior in plot_metagene.

**Comment by mjgeng** [comment]
I have made a new parameter called 'ticks' with a default value of 10, which specifies the x-axis labeling. Please let me know what you think. 

Examples:
`green <- ribo("green_6_10_2019.ribo")`
`plot_metagene(green, "start", 15,  40,  normalize = FALSE, tick = 10)`
![metagene_counts](https://user-images.githubusercontent.com/15066495/60129411-8ffbb780-975a-11e9-9e72-98dc0df75ebb.png)

If I want to change the 'tick' parameter from its default value of 10 to a new value of 20,
`plot_metagene(green, "start", 15,  40, normalize = FALSE, tick = 20)`
![metagene_tick_20](https://user-images.githubusercontent.com/15066495/60129560-e668f600-975a-11e9-962d-24ff1bf21be5.png)

**Comment by hakanozadam** [comment]
Ticks: Default and overriding are working!
Normalization is also working! 
It can also generate the plot from the data.table
