### ISSUE TITLE
plot_region_counts() percentage on barplots

### ISSUE THREAD

**Issue by hakanozadam** [ribosomeprofiling/riboR_alpha#7]
Let's put CDS percentages on the bar plot (say in the middle.)

This call
`plot_region_counts( green, range.lower = 28, range.upper = 32)`
did produce barplots properly but it didn't display the percentages.

**Comment by hakanozadam** [comment]
Can we have CDS percentageson the bar plot?

For example:
![green_region_counts](https://user-images.githubusercontent.com/6146520/59966621-80733900-94e4-11e9-99d5-4e9a593563a5.png)

**Comment by mjgeng** [comment]
![region_count_plot](https://user-images.githubusercontent.com/15066495/59978701-b24bd480-95a4-11e9-9c2a-9a1af4d2a09b.png)

I added the functionality. I may still need to find a better solution, as I did not align the data across the line. I think it may look a little distorted in the case that the data is not as clean.

**Comment by hakanozadam** [comment]
Let's figure out why the percentage values are different.

Are you excluding the junction values from your calculations?

Are you using this formula?
CDS_percentage = ( CDS /  ( CDS + UTR5 + UTR3  ) ) * 100

**Comment by mjgeng** [comment]
When I plot from read lengths 15 to 40, I get the following plot which matches the plot above.  I will look into aligning the data along the middle sometime tomorrow.

![all_lengths](https://user-images.githubusercontent.com/15066495/60060782-e4019000-96b7-11e9-91f6-135a7f30ed9a.png)

**Comment by hakanozadam** [comment]
Ah! I must have guessed! For different read lengths, we get (sightly) different values!
